FROM golang@sha256:fcdb3e42c5544e9682a635771eac76a698b66de79b1b50ec5b9ce5c5f14ad775
ARG SCALEWAY_CLI_VERSION="2.54.0"
ARG GOLANGCI_LINT_VERSION="2.11.4"

RUN apt-get update && apt-get install wget

RUN wget "https://github.com/scaleway/scaleway-cli/releases/download/v${SCALEWAY_CLI_VERSION}/scaleway-cli_${SCALEWAY_CLI_VERSION}_linux_amd64" -O /tmp/scaleway-cli && \
    chmod +x /tmp/scaleway-cli && \
    mv /tmp/scaleway-cli /bin/scw && \
    scw version
RUN wget "https://github.com/golangci/golangci-lint/releases/download/v${GOLANGCI_LINT_VERSION}/golangci-lint-${GOLANGCI_LINT_VERSION}-linux-amd64.tar.gz" -O /tmp/golangci-lint.tar.gz && \
    tar -xf /tmp/golangci-lint.tar.gz -C /tmp && \
    mv /tmp/golangci-lint-${GOLANGCI_LINT_VERSION}-linux-amd64/golangci-lint /tmp/golangci-lint && \
    chmod +x /tmp/golangci-lint && \
    mv /tmp/golangci-lint /bin/golangci-lint && \
    golangci-lint --version
RUN go install github.com/a-h/templ/cmd/templ@v0.3.1001 && \
    templ version
RUN rm -rf /tmp/* && mkdir /src
WORKDIR /src
